/accre/arch/easybuild/software/BinDist/Anaconda3/2019.10/lib/python3.7/site-packages/pandas/core/series.py:853: RuntimeWarning: divide by zero encountered in log2
  result = getattr(ufunc, method)(*inputs, **kwargs)
Traceback (most recent call last):
  File "/accre/arch/easybuild/software/BinDist/Anaconda3/2019.10/lib/python3.7/site-packages/pandas/core/indexes/multi.py", line 1295, in _get_level_number
    level = self.names.index(level)
ValueError: 'mrca_2' is not in list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/dors/capra_lab/users/fongsl/enh_ages/landscape/ENCODE3_cCRE/HepG2/HepG2_ELS.py", line 661, in <module>
    plot_heatmap(comp, test)
  File "/dors/capra_lab/users/fongsl/enh_ages/landscape/ENCODE3_cCRE/HepG2/HepG2_ELS.py", line 635, in plot_heatmap
    index = "tf", columns = [ "mrca_2", "taxon2"], values = 'log2') # pivot only the significant results
  File "/accre/arch/easybuild/software/BinDist/Anaconda3/2019.10/lib/python3.7/site-packages/pandas/core/reshape/pivot.py", line 430, in pivot
    return indexed.unstack(columns)
  File "/accre/arch/easybuild/software/BinDist/Anaconda3/2019.10/lib/python3.7/site-packages/pandas/core/series.py", line 3745, in unstack
    return unstack(self, level, fill_value)
  File "/accre/arch/easybuild/software/BinDist/Anaconda3/2019.10/lib/python3.7/site-packages/pandas/core/reshape/reshape.py", line 402, in unstack
    return _unstack_multiple(obj, level, fill_value=fill_value)
  File "/accre/arch/easybuild/software/BinDist/Anaconda3/2019.10/lib/python3.7/site-packages/pandas/core/reshape/reshape.py", line 324, in _unstack_multiple
    clocs = [index._get_level_number(i) for i in clocs]
  File "/accre/arch/easybuild/software/BinDist/Anaconda3/2019.10/lib/python3.7/site-packages/pandas/core/reshape/reshape.py", line 324, in <listcomp>
    clocs = [index._get_level_number(i) for i in clocs]
  File "/accre/arch/easybuild/software/BinDist/Anaconda3/2019.10/lib/python3.7/site-packages/pandas/core/indexes/multi.py", line 1298, in _get_level_number
    raise KeyError("Level %s not found" % str(level))
KeyError: 'Level mrca_2 not found'
